export const CONFIG = {
  PORT: parseInt(process.env.PORT || "3000", 10),

  REDIS_URL: process.env.REDIS_URL || "redis://localhost:6379",

  KEY_PREFIX: "rr:",

  TOPIC_LEADERBOARD: "leaderboard",

  WEEK_TTL: 60 * 60 * 24 * 14,

  SESSION_TTL: 60 * 30,

  TICK_INTERVAL_MS: 250,

  GHOST_TTL: 60 * 60 * 24 * 90,

  LEADERBOARD_CACHE_TTL: 5,

  ANTI_CHEAT: {
    SCORE_PER_UNIT_SPEED: 165,
    SPEED_BASE: 0.8,
    SPEED_PER_LEVEL: 0.5,
    SPEED_ACCEL_MAX: 0.3,
    SPEED_GRACE: 0.2,
    SCORE_UNITS_PER_LEVEL: 6000,
    SCORE_TOLERANCE: 3.0,
    SCORE_MONOTONIC_GRACE: 50,
    TICK_INTERVAL_MAX: 10,
    CLOCK_DRIFT_MS: 30000,
    LEVEL_TOLERANCE: 2,
    MIN_TICK_COUNT: 2,
  },

  USERNAME: {
    MIN_LENGTH: 3,
    MAX_LENGTH: 16,
    PATTERN: /^[a-zA-Z0-9]([a-zA-Z0-9_-]*[a-zA-Z0-9])?$/,
  },

  WEEK_CHECK_INTERVAL_MS: 60_000,

  TOP_LEADERBOARD_LIMIT: 100,
} as const
